server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: user-service #路由id，自定义，必须唯一
          uri: lb://userservice #lb（负载均衡），路由的目标地址
          predicates: #路由断言，判断请求路径是否符合路由规则的条件
            - Path=/user/** #这个是按路径匹配，只要以/user/开头都符合规则
#          filters:
#            - AddRequestHeader=Truth, Freaking awesome
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
      globalcors:
        add-to-simple-url-handler-mapping: true #解决options请求被拦截问题
        cors-configurations:
          '[/**]':
            allowedOrigins: #允许那些网站的跨域请求
              - "http://localhost:8083"
            allowedMethods: #允许跨域的ajax请求
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" #允许跨域的请求中携带的请求头信息
            allowedCredentials: true #是否允许携带cookie
            maxAge: 360000 #这次跨域检测的有效期