server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/course_design?useSSL=false&&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice
  cloud:
    nacos:
      server-addr: localhost:8848 #nacos服务地址
      discovery:
#        cluster-name: HZ #集群名称
#        namespace: 4a9e0cce-71ff-440c-81db-5ca2644e6f45 #命名空间
        ephemeral: false
  rabbitmq:
    host: 121.40.137.246
    port: 5672
    virtual-host: /
    username: root
    password: root
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:8089/eureka/
userservice:
  ribbon:
      NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
    #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #负载均衡策略
ribbon:
  eager-load:
    enabled: true
    clients:
      - userservice
      - orderservice
#feign:
#  client:
#    config:
#      default:
#        loggerlevel: FULL